### ISSUE TITLE
JOSS review: Instructions for glottomap and glottofiltermap

### ISSUE THREAD

**Issue by skalyan91** [SietzeN/glottospace#107]
There needs to be better documentation on how to use interactive selection in `glottomap()` and `glottofiltermap()`. I can’t figure out how to select languages in the selection interface: whenever I click a dot, I get a pop-up with metadata about that language, but I don’t see the selection being saved anywhere, and after I click “Done”, if I evaluate the `selected` object I get `NULL`.

**Comment by SietzeN** [comment]
Hi @skalyan91 
This is because the default selection method was set to draw, for which a shape needs to be drawn around the points. I've now changed the default selection mode to 'click'. I also added some lines in the documentation of both functions to make this more explicit. Thanks!
