### ISSUE TITLE
Dialect Glottocodes not recognized

### ISSUE THREAD

**Issue by macastelo** [SietzeN/glottospace#124]
It seems that not all glottocodes are recognized by glottospace.
Certain glottocodes are associated with languoid dialects but are not recognized as a "TRUE" glottocode (e.g. chan1322, cuev1238, guaj1255, kipe1235, mara1408) nor do they map despite having coordinates associated with them. 

Some codes in Glottolog are not associated with a coordinate like tapa1261, which makes sense. 

I don't know if this is an issue with Glottolog's system or with Glottospace.

**Comment by xrotwang** [comment]
Maybe glottoscope doesn't recognize languoids from Glottolog's "Unclassifiable" pseudo-family (see https://glottolog.org/glottolog/glottologinformation for details).

**Comment by SietzeN** [comment]
Hi!
If you run glottoget() without any arguments, the 'glottobase' data is loaded. This is a spatially enhanced and restructured version of glottolog **which keeps only L1 languages**. L1 languages do not include bookkeeping, unclassifiable and sign languages (etc.). If you want to keep non-L1 languages, you could run glottoget("glottolog") and subsequently run glottobooster(). Check the helpfile of glottobooster for more details and examples (by typing:  ?glottobooster ). Subsequently you can plot these languages (if they have coordinates associated with them).
