### ISSUE TITLE
data the glottospace downloads should be stored somewhere that's not ~

### ISSUE THREAD

**Issue by SimonGreenhill** [SietzeN/glottospace#13]
I just noticed that glottospace wrote the glottolog download and some shape files to my home directory, it would be better to use something like [rappdirs::user_cache_dir](https://www.rdocumentation.org/packages/rappdirs/versions/0.3.3/topics/user_cache_dir)

**Comment by SietzeN** [comment]
Hi Simon, 

Thanks again for raising this issue. The downloaded glottolog data is now stored using rappdirs::user_cache_dir(), thanks for the suggestion! The default download location is now the CLDF from zenodo. Now the package checks which version of glottolog is available locally, and downloads a newer version in case it is available.

I will also check which other data is saved in the home directory. I was thinking that the default location for some files should be the working directory, but I will double check. 

Cheers!
Sietze

**Comment by SimonGreenhill** [comment]
thanks! 👍

**Comment by SietzeN** [comment]
I double checked: all files that users download are stored in working directory, all behind-the-scenes files are stored with rappdirs
