### ISSUE TITLE
no package called ‘sf’

### ISSUE THREAD

**Issue by alenawitzlack** [SietzeN/glottospace#130]
Hey Sietze,

I recently reinstalled the package (with all dependencies) and get the following error message relatively early on:

`glottomap(continent = "South America", color = "isolate")`

`Error in loadNamespace(x) : there is no package called ‘sf’`

An attempt to install the `sf` package (whatever it is) fails.

Any idea what's going on?

Alena

**Comment by SietzeN** [comment]
Hi Alena!

Thanks for your message.

This should be easy to solve by running:

install.packages("sf")

Cheers!
Sietze

Van: alenawitzlack ***@***.***>
Verzonden: dinsdag 30 mei 2023 12:53
Aan: SietzeN/glottospace ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [SietzeN/glottospace] no package called ‘sf’ (Issue #130)

U ontvangt niet vaak e-mail van ***@***.*** Meer informatie over waarom dit belangrijk is<https://aka.ms/LearnAboutSenderIdentification>

Hey Sietze,

I recently reinstalled the package (with all dependencies) and get the following error message relatively early on:

glottomap(continent = "South America", color = "isolate")

Error in loadNamespace(x) : there is no package called ‘sf’

An attempt to install the sf package (whatever it is) fails.

Any idea what's going on?

Alena

**Comment by alenawitzlack** [comment]
Funny, it's what I tried first thing yesterday and it failed. But it's working now! 
Thanks!
Alena

**Comment by SietzeN** [comment]
Great!

Van: alenawitzlack ***@***.***>
Verzonden: woensdag 31 mei 2023 09:49
Aan: SietzeN/glottospace ***@***.***>
CC: Norder, S.J. (Sietze) ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [SietzeN/glottospace] no package called ‘sf’ (Issue #130)

U ontvangt niet vaak e-mail van ***@***.*** Meer informatie over waarom dit belangrijk is<https://aka.ms/LearnAboutSenderIdentification>

Funny, it's what I tried first thing yesterday and it failed. But it's working now!
Thanks!
Alena
