### ISSUE TITLE
Shortcut for variable names in glottocreate

### ISSUE THREAD

**Issue by rikvangijn** [SietzeN/glottospace#16]
Would it be possible to include the option for the variables= argument in glottocreate to take arguments like F01:F18 to create 18 consecutively numbered variable names?

**Comment by SietzeN** [comment]
Yes, sure:
glottocreate_subdata(glottocodes = c("yucu1253", "tani1257"), variables = paste0("F", 1:18), groups = c("a", "b"), n = 5)
