### ISSUE TITLE
Request: Add D-Place data to glottoget

### ISSUE THREAD

**Issue by SietzeN** [SietzeN/glottospace#32]
See code in isolates project

**Comment by SietzeN** [comment]
glottoget_cldf() : works for WALS, but not for D-PLACE. [Lines 272-275](https://github.com/SietzeN/glottospace/blob/0ed6cca94480bb857032a75c06a0c2de11ebf75f/R/glottoget.R#L272) This can be improved..

**Comment by xrotwang** [comment]
The proper way to read CLDF data would entail
- discovering the metadata file (cf. https://github.com/cldf/pycldf/blob/ee7a8028c6792f946e1995f3eec8a38b84289a36/src/pycldf/dataset.py#L1086-L1117)
- consulting the [metadata file](https://github.com/cldf/cldf#cldf-metadata-file) to determine
  - the CSV dialect used for the data files
  - the filenames of the tables corresponding to CLDF components
- reading the CSV data - preferably casting the data to the datatypes specified in the metadata

I guess all this would best be handled by a separate package - e.g. `rcldf`.
