### ISSUE TITLE
glottocode_exists undefined exports: glottocode_exists Error: loading failed

### ISSUE THREAD

**Issue by chris-english** [SietzeN/glottospace#39]
> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.3 LTS

Matrix products: default
BLAS:   /usr/local/lib/R/lib/libRblas.so
LAPACK: /usr/local/lib/R/lib/libRlapack.so
All listed imports installed.

finding level-2 HTML links ... done

Rd warning: /home/chris/r_TMPDIR/RtmpyYkPro/R.INSTALL3404c5dd5e876/glottospace/man/glottobooster.Rd:18: missing link ‘glottoget_glottolog()’ [comes up another 15 or so times]
Finalizes with:
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘glottospace’ in namespaceExport(ns, exports):
 undefined exports: glottocode_exists
Error: loading failed

I note you were working on 'glottocode_exists.R' probably just before I attempted install. Any thoughts, and look forward to working with your package.

**Comment by SietzeN** [comment]
Hi Chris,

Thanks for the note. You're right I just renamed that function and broke some things because of that. I think it's fixed now.

Thanks for using my package!

Cheers!
Sietze

**Comment by chris-english** [comment]
* DONE (glottospace)
