### ISSUE TITLE
Resolve WALS dataset from DOI

### ISSUE THREAD

**Issue by xrotwang** [SietzeN/glottospace#51]
While it may be sufficient for the context of this package to rely on WALS data being available on Zenodo, the "proper" way to infer its location would be resolving the DOI URL https://doi.org/10.5281/zenodo.3606197 - and not hardcoding the Zenodo URL in https://github.com/SietzeN/glottospace/blob/9a4d234530280f1baf47551f84f4f20e2afb42bf/R/glottoget_wals.R#L77

**Comment by xrotwang** [comment]
The hardcoded Zenodo URL is also duplicated here https://github.com/SietzeN/glottospace/blob/9a4d234530280f1baf47551f84f4f20e2afb42bf/R/glottoget_wals.R#L106

**Comment by xrotwang** [comment]
Dito for Glottolog: https://github.com/SietzeN/glottospace/blob/9a4d234530280f1baf47551f84f4f20e2afb42bf/R/glottoget.R#L229

**Comment by SietzeN** [comment]
Hi Robert!

Thanks for your comment. As I understand the zenodo structure, this would always refer to the latest version of the data. 

The benefit of using "https://zenodo.org/api/records/3606197" is that it's a direct download link. If we would use the DOI, how would you suggest to resolve to the latest version?

Cheers!
Sietze

**Comment by xrotwang** [comment]
The DOI URL will also always resolve to the latest version:
```shell
$ curl -I  https://doi.org/10.5281/zenodo.3606197
HTTP/2 302 
location: https://zenodo.org/record/3606197
```

The DOI doesn't depend on the dataset being hosted with Zenodo. I.e. if Zenodo would be "bought by Elsevier", they might redirect all DOIs and decommission the Zenodo URLs. But since you are relying on a particular response from the Zenodo API anyway, changing to the DOI will probably not make things less brittle. So, I guess things are ok the way they are :)

**Comment by SietzeN** [comment]
Ok, great. Thanks. I'll keep it the way it is then!
