### ISSUE TITLE
Glottolog download data is fetched from the wrong URL

### ISSUE THREAD

**Issue by xrotwang** [SietzeN/glottospace#52]
Here
https://github.com/SietzeN/glottospace/blob/9a4d234530280f1baf47551f84f4f20e2afb42bf/R/glottoget.R#L316
it says that `https://cdstar.shh.mpg.de/bitstreams/EAEA0-E62D-ED67-FD05-0/` is the location of the latest version of Glottolog downloads. But that is not true.
1. We recently had to change the hostname of this fileserver to `cdstar.eva.mpg.de`.
2. Downloads will be archived as bitstreams for a new object for each Glottolog release, i.e. the path in the URL will change. For Glottolog 4.5, the object ID is [EAEA0-F8BB-0AB6-96FA-0](https://github.com/clld/glottolog3/blob/539bb842cea3de308b89fd5526971e5563acec0d/glottolog3/static/downloads.json#L1432), and the downloads are listed here https://cdstar.eva.mpg.de/landing/EAEA0-F8BB-0AB6-96FA-0

**Comment by SietzeN** [comment]
Hi Robert,

Thanks for the note. This is function is only called in the rare case that the CLDF download fails. 

Is there a way to access the most recent version directly via one URL? If not, I will remove the function altogether, since we can also revert to the built-in glottolog dataset from CLDF.

Cheers!
Sietze

**Comment by xrotwang** [comment]
No, there is no stable, "knowable" URL for the most recent version. I'd also like to discourage using these "pre-compiled" download files, and ideally, `glottospace` helps with this, because it let's people make maps without having to muck around with CLDF directly :)

**Comment by SietzeN** [comment]
Ok, great to know. I remove the function and stick with the CLDF format.
