### ISSUE TITLE
specifications for continents

### ISSUE THREAD

**Issue by alenawitzlack** [SietzeN/glottospace#65]
Where does the specifications of continents come from (not from Glottolog) and how can one change it? 
glottomap(continent = "Europe", color = "isolate")
yield all of the Russian Federation including the ones in the Far East, as well as all sorts of languages in overseas territories.

![Screenshot 2022-02-21 at 16 51 03](https://user-images.githubusercontent.com/7422504/154988379-a17edd12-7ebe-44f1-80db-80026af67b0c.png)

**Comment by SietzeN** [comment]
The countries and continents come from naturalearth (https://www.naturalearthdata.com/). You can also search the data by using Glottolog macroareas. For example: macroarea = "Eurasia". 


#To subset parts of a selection, you could do:
eur <- glottofilter(continent = "Europe")
# Exclude Russia:
eurnr <- glottofilter(glottodata = eur, colname = "country", drop = "Russia")
# Select the European languages you're interested in and click 'done':
eursel <- glottofiltermap(glottodata = eurnr)
Make a map:
glottomap(eursel, color = "isolate", type = "dynamic")
