### ISSUE TITLE
glottoget default 

### ISSUE THREAD

**Issue by HedvigS** [SietzeN/glottospace#67]
I'd just like it clarified what happens when you use glottoget() without specifying anything further. It looks like a merger of some parts of glottolog and wals?

**Comment by HedvigS** [comment]
Where do continent, geometry and sovereigntycome from? It looks like the code says it's from wals, but I've never seen that in wals before.

**Comment by SietzeN** [comment]
Hi Hedvig! 
Thanks for the question. The answer to this question is in the help page of glottoget. You can access it by typing: ?glottoget

The help page says: 
"glottobase" - Default option, an spatially enhanced version of glottolog. See glottobooster for details.

I will add a line to the help page clarifying this further.

The spatial information are obtained from Natural Earth: https://www.naturalearthdata.com/
