### ISSUE TITLE
glottoget() feedback version name also when download = F

### ISSUE THREAD

**Issue by HedvigS** [SietzeN/glottospace#68]
glottoget() has some troubles with the download argument. I'd need to specify a dirpath for it to work, even if that dirpath doesn't exist. It's to do with utils::download.file(). I think a quick fix would involve tempfile(). I'll have a go at fixing it.

fail
```
 df <- glottoget(glottodata = "glottolog", download = TRUE)
Are you sure you want to download Glottolog data? 
 Press [enter] to continue
Glottolog data downloaded (glottolog v4.5). This is the most recent version available from https://zenodo.org/api/records/3260727
Error in file(file, "rt") : invalid 'description' argument
In addition: Warning messages:
1: In utils::download.file(file.path(url), destfile = filepath) :
  URL https://zenodo.org/api/files/02398938-1781-4518-9cdd-cc1378461ae9/glottolog/glottolog-cldf-v4.5.zip: cannot open destfile '/var/folders/2r/drwc5p6n26ncm5cws9qsntrw0000gp/T//Rtmp7hqQJk/file28269782c82', reason 'No such file or directory'
2: In utils::download.file(file.path(url), destfile = filepath) :
  download had nonzero exit status
3: In utils::unzip(zipfile = filepath, exdir = dirpath) :
  error 1 in extracting from zip file
```

success when specifying non-existing dirpath
```

df <- glottoget(glottodata = "glottolog", download = TRUE, dirpath = "random")
Are you sure you want to download Glottolog data? 
 Press [enter] to continue
trying URL 'https://zenodo.org/api/files/02398938-1781-4518-9cdd-cc1378461ae9/glottolog/glottolog-cldf-v4.5.zip'
Content type 'application/octet-stream' length 7737229 bytes (7.4 MB)
==================================================
downloaded 7.4 MB

Glottolog data downloaded (glottolog v4.5). This is the most recent version available from https://zenodo.org/api/records/3260727
```

**Comment by HedvigS** [comment]
Right, I had a closer look at the code for glottoget() and glottoget_glottolog() and it's more complicated than that.

I'm not sure I understand the point of specifying dirpaths in so many places, would users load the data to an object in their environment and then manipulate it? Why by default expect to write something to file?

**Comment by HedvigS** [comment]
And why does it need to be a new unique dirpath? Maybe I don't mind writing over the previous contents?

**Comment by HedvigS** [comment]
Sorry... I was just thinking again and it's all about this download argument. of course download wants a dirpath. What I want is for the same things about versions to kick in (as discussed in #55 ) when you're not using the download argument.

**Comment by HedvigS** [comment]
Given what we talked about in #55 I would have expected this:

`glottospace::glottoget(glottodata = "glottolog")`

To give me a similar feedback as `glottospace::glottoget(glottodata = "glottolog", download = T)` does in terms of version and citation.

**Comment by SietzeN** [comment]
This is closed with previous commit. ?glottolog or ?wals gives information about version and citation.

**Comment by HedvigS** [comment]
Right, sorry. So. I understand that ?glottolog gives this information, but can 

`glottospace::glottoget(glottodata = "glottobase")`

please also report this information when it runs?
