### ISSUE TITLE
Russia's Chukotka cause troubles

### ISSUE THREAD

**Issue by agricolamz** [SietzeN/glottospace#7]
It is well known problem that on the standard maps Russia's Chukotka cause a lot of troubles, since it is not merged together with the main land.

So from the following code:
```
library(glottospace)
glottomap(country = "Russia")
```
I got the following result:

![image](https://user-images.githubusercontent.com/15956515/137115047-5a8f3938-457d-4ea8-a8b0-1daa0ef4c6dd.png)

```
packageVersion("glottospace")
[1] ‘0.0.1’
```

**Comment by SietzeN** [comment]
Hi! 
Thanks again, these are certainly on my wish list but are currently not (yet) implemented. I made a note of both your requests.
