### ISSUE TITLE
JOSS review: Software paper

### ISSUE THREAD

**Issue by skalyan91** [SietzeN/glottospace#98]
Hi! I’m currently reviewing this package for the Journal of Open Source Software.

One of the requirements for the paper is to “describe how this software compares to other commonly-used packages”. Currently the paper mentions the packages that the glottospace package builds on, but it doesn’t mention other similar packages. This is understandable, as I don’t think there is any other package that does all of what glottospace does! However, I think you should consider mentioning at least the following packages, which also provide access to data from Glottolog and/or WALS:
- [lingtypology](https://docs.ropensci.org/lingtypology/), by George Moroz
- [lingtypR](https://gitlab.com/laurabecker/lingtypr), by Laura Becker
- [qlcData](https://github.com/cysouw/qlcData), by Michael Cysouw

Also, as mentioned in the [review thread](https://github.com/openjournals/joss-reviews/issues/4303), the “References” section is currently empty; see there for further discussion.

**Comment by SietzeN** [comment]
Hi @skalyan91,
I've now added a reference to these packages and the reference section compiles now.
Cheers!

**Comment by skalyan91** [comment]
@SietzeN The paper at https://github.com/openjournals/joss-papers/blob/joss.04303/joss.04303/10.21105.joss.04303.pdf (which I recompiled just now) is still missing the references, and does not mention the packages I pointed out. Am I looking in the wrong place?

**Comment by SietzeN** [comment]
Hi @skalyan91!

Thanks for your mail! That's strange, I've implemented your suggestions and recompiled the paper to test it. The markdown file is here: https://github.com/SietzeN/glottospace/blob/joss_revision/paper.md I'm not sure why it doesn't work. I'll also reply on the JOSS GitHub.
Thanks!
p.s. I'll be away for two weeks, so my reply might take a bit longer.
